#!/usr/bin/env python3
"""
Accuracy comparison: Python TMU vs Rust tmu-rs for the new model types.

Loads shared binary data from data/cmp_*.bin (generated by gen_shared_data.py)
so that Rust and Python train/evaluate on bit-identical samples.

  1. TMRegressor     — continuous output (count function, threshold=100)
  2. ConvolutionalTM 1-D — position-invariant XOR (12 features, kernel=2)
  3. ConvolutionalTM 2-D — fixed-position vertical XOR on 2×4 images (3 patches)
  4. TMCompositeClassifier — ensemble on 4-class XOR

Usage:
  python scripts/gen_shared_data.py          # run once first
  python scripts/compare_new_models.py       # all models
  python scripts/compare_new_models.py --regressor
  python scripts/compare_new_models.py --conv
  python scripts/compare_new_models.py --conv2d
  python scripts/compare_new_models.py --composite
"""
import argparse
import pathlib
import sys

try:
    import numpy as np
except ImportError:
    sys.exit("ERROR: numpy required — pip install numpy")

DATA = pathlib.Path("data")

# ── shared data loader ────────────────────────────────────────────────────────

def _load(name, split, dtype, shape):
    path = DATA / f"cmp_{name}_{split}.bin"
    if not path.exists():
        sys.exit(
            f"ERROR: missing {path}\n"
            "Run:  python scripts/gen_shared_data.py"
        )
    arr = np.frombuffer(path.read_bytes(), dtype=np.dtype(dtype).newbyteorder("<"))
    return arr.reshape(shape)


def load_X(name, split, n, d):
    return _load(f"{name}_X", split, np.uint8, (n, d))

def load_y_f64(name, split, n):
    return _load(f"{name}_y", split, np.float64, (n,))

def load_y_u32(name, split, n):
    return _load(f"{name}_y", split, np.uint32, (n,))


# ── 1. TMRegressor ────────────────────────────────────────────────────────────

def run_regressor():
    try:
        from tmu.models.regression.vanilla_regressor import TMRegressor
    except ImportError:
        print("[regressor] SKIP — tmu not installed or missing TMRegressor")
        return

    N_FEATURES = 20
    THRESHOLD  = 100
    N_CLAUSES  = 200
    S          = 3.0
    N_EPOCHS   = 60
    SCALE      = THRESHOLD / 5.0

    X_tr = load_X("regressor", "train", 5000, N_FEATURES).astype(np.uint32)
    y_tr = load_y_f64("regressor", "train", 5000)
    X_te = load_X("regressor", "test",  1000, N_FEATURES).astype(np.uint32)
    y_te = load_y_f64("regressor", "test",  1000)

    tm = TMRegressor(
        number_of_clauses=N_CLAUSES,
        T=THRESHOLD,
        s=S,
        number_of_state_bits_ta=8,
        weighted_clauses=True,
        platform="CPU",
    )

    print(f"\n{'─'*60}")
    print(f"  Python TMU  TMRegressor")
    print(f"  {N_FEATURES} features · {N_CLAUSES} clauses · T={THRESHOLD} · s={S}")
    print(f"  Target: count(features 0..4) × {SCALE:.0f}  →  y ∈ {{0,20,40,60,80,100}}")
    print(f"  (shared data from data/cmp_regressor_*.bin)")
    print(f"{'─'*60}")
    print(f"{'epoch':>5}  {'train MAE':>10}  {'test MAE':>10}")

    for epoch in range(1, N_EPOCHS + 1):
        tm.fit(X_tr, y_tr)
        if epoch % 5 == 0 or epoch == 1:
            tr_mae = float(np.mean(np.abs(tm.predict(X_tr) - y_tr)))
            te_mae = float(np.mean(np.abs(tm.predict(X_te) - y_te)))
            print(f"{epoch:>5}  {tr_mae:>10.3f}  {te_mae:>10.3f}")

    preds_te = tm.predict(X_te)
    final_mae  = float(np.mean(np.abs(preds_te - y_te)))
    final_rmse = float(np.sqrt(np.mean((preds_te - y_te) ** 2)))
    print(f"\nFinal test MAE:  {final_mae:.3f}")
    print(f"Final test RMSE: {final_rmse:.3f}")


# ── 2. ConvolutionalTM 1-D ────────────────────────────────────────────────────

def run_convolutional():
    try:
        from tmu.models.classification.vanilla_classifier import TMClassifier
    except ImportError:
        print("[convolutional] SKIP — tmu not installed or missing TMClassifier")
        return

    N_FEATURES  = 4
    KERNEL_SIZE = 2
    STRIDE      = 1
    N_PATCHES   = (N_FEATURES - KERNEL_SIZE) // STRIDE + 1   # 3
    N_CLAUSES   = 100
    THRESHOLD   = 50
    S           = 3.5
    N_EPOCHS    = 60

    X_tr = load_X("conv", "train", 5000, N_FEATURES).astype(np.uint32)
    y_tr = load_y_u32("conv", "train", 5000)
    X_te = load_X("conv", "test",  1000, N_FEATURES).astype(np.uint32)
    y_te = load_y_u32("conv", "test",  1000)

    # Expand training set: one copy per patch position (weight tying).
    X_tr_exp_list, y_tr_exp_list = [], []
    for p in range(N_PATCHES):
        X_tr_exp_list.append(X_tr[:, p * STRIDE:p * STRIDE + KERNEL_SIZE])
        y_tr_exp_list.append(y_tr)
    X_tr_exp = np.concatenate(X_tr_exp_list, axis=0)
    y_tr_exp = np.concatenate(y_tr_exp_list, axis=0)

    tm = TMClassifier(
        number_of_clauses=N_CLAUSES * 2,
        T=THRESHOLD,
        s=S,
        number_of_state_bits_ta=8,
        weighted_clauses=True,
        platform="CPU",
    )

    print(f"\n{'─'*60}")
    print(f"  Python TMU  ConvolutionalTM 1-D (patch-expanded training)")
    print(f"  {N_FEATURES} features · kernel={KERNEL_SIZE} · stride={STRIDE} · "
          f"{N_PATCHES} patches")
    print(f"  {N_CLAUSES} clauses/class · T={THRESHOLD} · s={S}")
    print(f"  Label: x[0] XOR x[1]  (signal always at patch 0; patches 1,2 = noise)")
    print(f"  (shared data from data/cmp_conv_*.bin)")
    print(f"{'─'*60}")
    print(f"{'epoch':>5}  {'train acc':>10}  {'test acc':>10}")

    def _vote(X, n):
        votes = np.zeros((n, 2), dtype=int)
        for p in range(N_PATCHES):
            patch = X[:, p * STRIDE:p * STRIDE + KERNEL_SIZE]
            preds = tm.predict(patch)
            votes[np.arange(n), preds] += 1
        return votes.argmax(axis=1)

    best_te = 0.0
    for epoch in range(1, N_EPOCHS + 1):
        tm.fit(X_tr_exp, y_tr_exp)
        if epoch % 10 == 0 or epoch == 1:
            tr_acc = float(np.mean(_vote(X_tr, len(X_tr)) == y_tr))
            te_acc = float(np.mean(_vote(X_te, len(X_te)) == y_te))
            best_te = max(best_te, te_acc)
            print(f"{epoch:>5}  {tr_acc:>10.4f}  {te_acc:>10.4f}")

    final_acc = float(np.mean(_vote(X_te, len(X_te)) == y_te))
    print(f"\nFinal test accuracy: {final_acc:.4f}")
    print(f"Best  test accuracy: {best_te:.4f}  (across evaluated epochs)")


# ── 3. ConvolutionalTM 2-D ────────────────────────────────────────────────────

def run_convolutional_2d():
    try:
        from tmu.models.classification.vanilla_classifier import TMClassifier
    except ImportError:
        print("[conv2d] SKIP — tmu not installed or missing TMClassifier")
        return

    # 2×4 image, 2×2 patch, stride=1 → 3 patches (same count as 1-D case).
    # Signal at patch (0,0): label = x[0,0] XOR x[1,0]  (vertical XOR).
    # Using 3 patches keeps the noise ratio identical to the 1-D comparison.
    INPUT_ROWS   = 2
    INPUT_COLS   = 4
    PATCH_ROWS   = 2
    PATCH_COLS   = 2
    STRIDE       = 1
    N_PATCH_ROWS = (INPUT_ROWS - PATCH_ROWS) // STRIDE + 1   # 1
    N_PATCH_COLS = (INPUT_COLS - PATCH_COLS) // STRIDE + 1   # 3
    N_PATCHES    = N_PATCH_ROWS * N_PATCH_COLS                # 3
    PATCH_SIZE   = PATCH_ROWS * PATCH_COLS                    # 4
    N_FEATURES   = INPUT_ROWS * INPUT_COLS                    # 8
    N_CLAUSES    = 100
    THRESHOLD    = 50
    S            = 3.5
    N_EPOCHS     = 60

    X_tr = load_X("conv2d", "train", 5000, N_FEATURES).astype(np.uint32)
    y_tr = load_y_u32("conv2d", "train", 5000)
    X_te = load_X("conv2d", "test",  1000, N_FEATURES).astype(np.uint32)
    y_te = load_y_u32("conv2d", "test",  1000)

    def _extract_patch(X, pr, pc):
        """Extract 2-D patch at (pr,pc) from flattened images → (n, PATCH_SIZE)."""
        rows = []
        for r in range(PATCH_ROWS):
            start = (pr + r) * INPUT_COLS + pc
            rows.append(X[:, start:start + PATCH_COLS])
        return np.concatenate(rows, axis=1)

    # Expand training set: one copy per patch position.
    X_tr_exp_list, y_tr_exp_list = [], []
    for pr in range(N_PATCH_ROWS):
        for pc in range(N_PATCH_COLS):
            X_tr_exp_list.append(_extract_patch(X_tr, pr, pc))
            y_tr_exp_list.append(y_tr)
    X_tr_exp = np.concatenate(X_tr_exp_list, axis=0)
    y_tr_exp = np.concatenate(y_tr_exp_list, axis=0)

    tm = TMClassifier(
        number_of_clauses=N_CLAUSES * 2,
        T=THRESHOLD,
        s=S,
        number_of_state_bits_ta=8,
        weighted_clauses=True,
        platform="CPU",
    )

    print(f"\n{'─'*60}")
    print(f"  Python TMU  ConvolutionalTM 2-D (patch-expanded training)")
    print(f"  {INPUT_ROWS}×{INPUT_COLS} image · patch={PATCH_ROWS}×{PATCH_COLS} · "
          f"stride={STRIDE} · {N_PATCHES} patches")
    print(f"  {N_CLAUSES} clauses/class · T={THRESHOLD} · s={S}")
    print(f"  Label: x[0,0] XOR x[1,0]  (vertical XOR, signal at patch (0,0))")
    print(f"  (shared data from data/cmp_conv2d_*.bin)")
    print(f"{'─'*60}")
    print(f"{'epoch':>5}  {'train acc':>10}  {'test acc':>10}")

    def _vote(X, n):
        votes = np.zeros((n, 2), dtype=int)
        for pr in range(N_PATCH_ROWS):
            for pc in range(N_PATCH_COLS):
                patch = _extract_patch(X, pr, pc)
                preds = tm.predict(patch)
                votes[np.arange(n), preds] += 1
        return votes.argmax(axis=1)

    best_te = 0.0
    for epoch in range(1, N_EPOCHS + 1):
        tm.fit(X_tr_exp, y_tr_exp)
        if epoch % 10 == 0 or epoch == 1:
            tr_acc = float(np.mean(_vote(X_tr, len(X_tr)) == y_tr))
            te_acc = float(np.mean(_vote(X_te, len(X_te)) == y_te))
            best_te = max(best_te, te_acc)
            print(f"{epoch:>5}  {tr_acc:>10.4f}  {te_acc:>10.4f}")

    final_acc = float(np.mean(_vote(X_te, len(X_te)) == y_te))
    print(f"\nFinal test accuracy: {final_acc:.4f}")
    print(f"Best  test accuracy: {best_te:.4f}  (across evaluated epochs)")


# ── 4. TMCompositeClassifier ──────────────────────────────────────────────────

def run_composite():
    try:
        from tmu.models.classification.vanilla_classifier import TMClassifier
    except ImportError:
        print("[composite] SKIP — tmu not installed or missing TMClassifier")
        return

    TMComposite = None
    try:
        from tmu.models.classification.composite_classifier import TMCompositeClassifier
        TMComposite = TMCompositeClassifier
    except ImportError:
        pass

    N_FEATURES    = 8
    N_CLASSES     = 4
    CLAUSES_EACH  = 20
    TOTAL_CLAUSES = 60
    THRESHOLD     = 20
    S             = 3.9
    N_EPOCHS      = 30

    X_tr = load_X("composite", "train", 5000, N_FEATURES).astype(np.uint32)
    y_tr = load_y_u32("composite", "train", 5000)
    X_te = load_X("composite", "test",  1000, N_FEATURES).astype(np.uint32)
    y_te = load_y_u32("composite", "test",  1000)

    print(f"\n{'─'*60}")
    print(f"  Python TMU  TMCompositeClassifier vs single")
    print(f"  {N_FEATURES} features · 4 classes · s={S} · 5% train noise")
    print(f"  (shared data from data/cmp_composite_*.bin)")

    if TMComposite is not None:
        composite = TMComposite()
        for _ in [10, 20, 30]:
            composite.add(TMClassifier(
                number_of_clauses=CLAUSES_EACH * N_CLASSES,
                T=THRESHOLD, s=S,
                number_of_state_bits_ta=8, weighted_clauses=True, platform="CPU",
            ))
        use_native = True
        print(f"  Composite: 3×{CLAUSES_EACH} clauses/class (native TMCompositeClassifier)")
    else:
        classifiers = [
            TMClassifier(
                number_of_clauses=CLAUSES_EACH * N_CLASSES,
                T=THRESHOLD, s=S,
                number_of_state_bits_ta=8, weighted_clauses=True, platform="CPU",
            )
            for _ in range(3)
        ]
        use_native = False
        print(f"  Composite: 3×{CLAUSES_EACH} clauses/class (manual ensemble)")

    single = TMClassifier(
        number_of_clauses=TOTAL_CLAUSES * N_CLASSES,
        T=THRESHOLD, s=S,
        number_of_state_bits_ta=8, weighted_clauses=True, platform="CPU",
    )

    print(f"  Single:    {TOTAL_CLAUSES} clauses/class")
    print(f"{'─'*60}")
    print(f"{'epoch':>5}  {'composite acc':>14}  {'single acc':>12}")

    def _composite_predict(X):
        if use_native:
            return composite.predict(X)
        votes = np.zeros((len(X), N_CLASSES), dtype=int)
        for clf in classifiers:
            preds = clf.predict(X)
            votes[np.arange(len(X)), preds] += 1
        return votes.argmax(axis=1)

    def _composite_fit(X, y):
        if use_native:
            composite.fit(X, y)
        else:
            for clf in classifiers:
                clf.fit(X, y)

    for epoch in range(1, N_EPOCHS + 1):
        _composite_fit(X_tr, y_tr)
        single.fit(X_tr, y_tr)
        if epoch % 5 == 0 or epoch == 1:
            ca = float(np.mean(_composite_predict(X_te) == y_te))
            sa = float(np.mean(single.predict(X_te) == y_te))
            print(f"{epoch:>5}  {ca:>14.4f}  {sa:>12.4f}")

    ca = float(np.mean(_composite_predict(X_te) == y_te))
    sa = float(np.mean(single.predict(X_te) == y_te))
    print(f"\nFinal composite accuracy: {ca:.4f}")
    print(f"Final single accuracy:    {sa:.4f}")


# ── entry point ───────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(
        description="Compare Python TMU vs Rust tmu-rs for new model types.\n"
                    "Run python scripts/gen_shared_data.py first.",
    )
    p.add_argument("--regressor",  action="store_true")
    p.add_argument("--conv",       action="store_true")
    p.add_argument("--conv2d",     action="store_true")
    p.add_argument("--composite",  action="store_true")
    args = p.parse_args()

    run_all = not (args.regressor or args.conv or args.conv2d or args.composite)

    if run_all or args.regressor:
        run_regressor()
    if run_all or args.conv:
        run_convolutional()
    if run_all or args.conv2d:
        run_convolutional_2d()
    if run_all or args.composite:
        run_composite()


if __name__ == "__main__":
    main()
