//! Save/load support for trained models and the encoder (requires the `serde`
//! feature).
//!
//! Serialisation itself is generated by `serde`'s derive macros on each model;
//! this module only provides the thin framing that wraps a bincode payload:
//!
//! * a fixed 4-byte magic (`TMRS`), a `u32` format version, and a 1-byte type
//!   tag, so loading a foreign, corrupt, or wrong-kind file fails cleanly
//!   instead of decoding into a garbage model;
//! * the [`SaveLoad`] trait, whose provided methods are the entire public
//!   save/load surface — each model only declares its [`SaveLoad::TAG`].

use std::io::{self, Read, Write};
use std::path::Path;

use serde::de::DeserializeOwned;
use serde::Serialize;

/// File magic: identifies a tmu-rs serialised artifact.
pub(crate) const MAGIC: [u8; 4] = *b"TMRS";
/// Current on-disk format version. Bump on any incompatible layout change.
pub(crate) const VERSION: u32 = 1;

/// Type tags distinguishing the artifact kinds.
pub(crate) const TAG_VANILLA: u8 = 1;
pub(crate) const TAG_COALESCED: u8 = 2;
pub(crate) const TAG_AUTOENCODER: u8 = 3;
pub(crate) const TAG_ENCODER: u8 = 4;
pub(crate) const TAG_COALESCED_AUTOENCODER: u8 = 5;
pub(crate) const TAG_REGRESSOR: u8 = 6;
pub(crate) const TAG_CONVOLUTIONAL: u8 = 7;
pub(crate) const TAG_COMPOSITE: u8 = 8;

/// Build an `InvalidData` I/O error with a descriptive message.
pub(crate) fn bad(msg: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, msg.into())
}

/// Write magic + version + type tag.
pub(crate) fn write_header<W: Write>(w: &mut W, tag: u8) -> io::Result<()> {
    w.write_all(&MAGIC)?;
    w.write_all(&VERSION.to_le_bytes())?;
    w.write_all(&[tag])
}

/// Validate magic + version + type tag. Errors on any mismatch.
pub(crate) fn read_header<R: Read>(r: &mut R, expected_tag: u8) -> io::Result<()> {
    let mut magic = [0u8; 4];
    r.read_exact(&mut magic)?;
    if magic != MAGIC {
        return Err(bad("not a tmu-rs file (bad magic)"));
    }
    let mut ver = [0u8; 4];
    r.read_exact(&mut ver)?;
    let version = u32::from_le_bytes(ver);
    if version != VERSION {
        return Err(bad(format!(
            "unsupported tmu-rs format version {version} (expected {VERSION})"
        )));
    }
    let mut tag = [0u8; 1];
    r.read_exact(&mut tag)?;
    if tag[0] != expected_tag {
        return Err(bad(format!(
            "wrong artifact type: file tag {}, expected {expected_tag}",
            tag[0]
        )));
    }
    Ok(())
}

/// Write a tmu-rs header followed by the bincode-encoded `value`.
pub(crate) fn write_artifact<W: Write, T: Serialize>(
    w: &mut W,
    tag: u8,
    value: &T,
) -> io::Result<()> {
    write_header(w, tag)?;
    bincode::serialize_into(w, value).map_err(|e| bad(format!("serialisation failed: {e}")))
}

/// Validate the header (against `tag`) then bincode-decode the payload.
pub(crate) fn read_artifact<R: Read, T: DeserializeOwned>(r: &mut R, tag: u8) -> io::Result<T> {
    read_header(r, tag)?;
    bincode::deserialize_from(r).map_err(|e| bad(format!("deserialisation failed: {e}")))
}

/// Binary save/load for a trained artifact.
///
/// The (de)serialisation is generated by `serde`; implementers only declare
/// their [`TAG`](Self::TAG). Bring this trait into scope (`use tmu_rs::SaveLoad;`)
/// to call [`save`](Self::save) / [`load`](Self::load) on a model or encoder.
pub trait SaveLoad: Serialize + DeserializeOwned + Sized {
    /// The artifact type tag written into the file header.
    const TAG: u8;

    /// Serialise to `path` (truncating any existing file).
    fn save(&self, path: impl AsRef<Path>) -> io::Result<()> {
        let mut w = io::BufWriter::new(std::fs::File::create(path)?);
        self.write_to(&mut w)?;
        w.flush()
    }

    /// Load a value previously written by [`save`](Self::save).
    fn load(path: impl AsRef<Path>) -> io::Result<Self> {
        let mut r = io::BufReader::new(std::fs::File::open(path)?);
        Self::read_from(&mut r)
    }

    /// Write to any [`Write`] sink (used by [`save`](Self::save); handy for
    /// in-memory round-trips and tests).
    fn write_to<W: Write>(&self, w: &mut W) -> io::Result<()> {
        write_artifact(w, Self::TAG, self)
    }

    /// Read from any [`Read`] source (used by [`load`](Self::load)).
    fn read_from<R: Read>(r: &mut R) -> io::Result<Self> {
        read_artifact(r, Self::TAG)
    }
}
